# Production Environment Settings
api:
  replicaCount: 3
  env:
    nodeEnv: "production"
  db:
    configMapName: "prod-api-config"
    secretName: "prod-book-review-secrets"
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"