apiVersion: v1
kind: Service
metadata:
  name: book-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: book-ui
spec:
  type: {{ .Values.ui.service.type | default "ClusterIP" }}
  selector:
    app: book-ui
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: {{ .Values.ui.port }}
    protocol: TCP
    name: http