apiVersion: v1
kind: Service
metadata:
  name: book-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: book-api
spec:
  type: {{ .Values.api.service.type | default "ClusterIP" }}
  selector:
    app: book-api
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.port }}
    protocol: TCP
    name: http
