apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-review-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: book-review
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
  {{- if .Values.ingress.host }}
  - host: {{ .Values.ingress.host | quote }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: /
        pathType: {{ .Values.ingress.paths.ui.pathType | default "Prefix" }}
        backend:
          service:
            name: book-ui
            port:
              number: {{ .Values.ui.service.port }}
      - path: /api
        pathType: {{ .Values.ingress.paths.api.pathType | default "Prefix" }}
        backend:
          service:
            name: book-api
            port:
              number: {{ .Values.api.service.port }}